#!/bin/bash

apt-get remove nginx nginx-common -y
apt-get update
apt-get install nginx -y
sed -i 's/user www-data/user nginx/' /etc/nginx/nginx.conf
sed -i 's/listen 80;/listen 8080;/g' /etc/nginx/sites-available/default
service nginx restart
